<?xml version="1.0" encoding="utf-8"?><Database Name="DATN" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-41KA3SC\SQLEXPRESS;Initial Catalog=DATN;Persist Security Info=True;User ID=sa" SettingsObjectName="DATN_NTH.My.MySettings" SettingsPropertyName="DATNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="AcountName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>